# 与服务端建立连接，跟上面的配置要对应
serverAddr = "pei.work.gd"
serverPort = 7000

# 配置Token鉴权，要与服务端一致
auth.method = "token"
auth.token = "you"

# 配置日志信息
log.level = "info"
log.to = "frpc.log"

# 该内网穿透起名为SSH，annotations中随便写了一些备注，基于TCP协议将本机的22端口映射到公网的8001
[[proxies]]
name = "Mongodb"
annotations = {title = "Mongodb远程连接", fuck = "test", desc = "annotations是该连接的备注信息，里面的key和val是随便写的，在服务端控制面板可以看到"}
type = "tcp"
localIP = "127.0.0.1"
localPort = 36213
remotePort = 50001
